<div class="face-layout"><i></i>
    <div class="i8face-list">
        <span title="微笑" class="fw_face_span" imgurl="{faceBasePath}default/images/face/weixiao.gif"></span>
        <span title="大笑" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ciya.gif"></span>
        <span title="花痴" class="fw_face_span" imgurl="{faceBasePath}default/images/face/se.gif"></span>
        <span title="傲慢" class="fw_face_span" imgurl="{faceBasePath}default/images/face/aoman.gif"></span>
        <span title="拜拜" class="fw_face_span" imgurl="{faceBasePath}default/images/face/zaijian.gif"></span>
        <span title="悲剧" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ai.gif"></span>
        <span title="鄙视" class="fw_face_span" imgurl="{faceBasePath}default/images/face/bishi.gif"></span>
        <span title="发呆" class="fw_face_span" imgurl="{faceBasePath}default/images/face/fadai.gif"></span>
        <span title="闭嘴" class="fw_face_span" imgurl="{faceBasePath}default/images/face/bizui.gif"></span>
        <span title="大哭" class="fw_face_span" imgurl="{faceBasePath}default/images/face/daku.gif"></span>
        <span title="大骂" class="fw_face_span" imgurl="{faceBasePath}default/images/face/zhouma.gif"></span>
        <span title="点头笑" class="fw_face_span" imgurl="{faceBasePath}default/images/face/hanxiao.gif"></span>
        <span title="汗" class="fw_face_span" imgurl="{faceBasePath}default/images/face/liuhan.gif"></span>
        <span title="惊恐" class="fw_face_span" imgurl="{faceBasePath}default/images/face/jingkong.gif"></span>
        <span title="敲打" class="fw_face_span" imgurl="{faceBasePath}default/images/face/qiaoda.gif"></span>
        <span title="抓狂" class="fw_face_span" imgurl="{faceBasePath}default/images/face/zhuakuang.gif"></span>
        <span title="奋斗" class="fw_face_span" imgurl="{faceBasePath}default/images/face/fengdou.gif"></span>
        <span title="鼓掌" class="fw_face_span" imgurl="{faceBasePath}default/images/face/guzhang.gif"></span>
        <span title="打哈欠" class="fw_face_span" imgurl="{faceBasePath}default/images/face/haqian.gif"></span>
        <span title="擦汗" class="fw_face_span" imgurl="{faceBasePath}default/images/face/cahan.gif"></span>
        <span title="尴尬" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ganga.gif"></span>
        <span title="怒" class="fw_face_span" imgurl="{faceBasePath}default/images/face/fanu.gif"></span>
        <span title="困" class="fw_face_span" imgurl="{faceBasePath}default/images/face/kun.gif"></span>
        <span title="白眼" class="fw_face_span" imgurl="{faceBasePath}default/images/face/baiyan.gif"></span>
        <span title="吃惊" class="fw_face_span" imgurl="{faceBasePath}default/images/face/jingyan.gif"></span>
        <span title="哼" class="fw_face_span" imgurl="{faceBasePath}default/images/face/nanguo.gif"></span>
        <span title="可怜" class="fw_face_span" imgurl="{faceBasePath}default/images/face/kelian.gif"></span>
        <span title="泪" class="fw_face_span" imgurl="{faceBasePath}default/images/face/liulei.gif"></span>
        <span title="害羞" class="fw_face_span" imgurl="{faceBasePath}default/images/face/haixiu.gif"></span>
        <span title="坏笑" class="fw_face_span" imgurl="{faceBasePath}default/images/face/huaixiao.gif"></span>
        <span title="左哼哼" class="fw_face_span" imgurl="{faceBasePath}default/images/face/zuohenhen.gif"></span>
        <span title="右哼哼" class="fw_face_span" imgurl="{faceBasePath}default/images/face/youhenhen.gif"></span>
        <span title="亲亲" class="fw_face_span" imgurl="{faceBasePath}default/images/face/qinqin.gif"></span>
        <span title="吓" class="fw_face_span" imgurl="{faceBasePath}default/images/face/xia.gif"></span>
        <span title="大兵" class="fw_face_span" imgurl="{faceBasePath}default/images/face/dabin.gif"></span>
        <span title="酷" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ku.gif"></span>
        <span title="得意" class="fw_face_span" imgurl="{faceBasePath}default/images/face/deyi.gif"></span>
        <span title="睡觉" class="fw_face_span" imgurl="{faceBasePath}default/images/face/shui.gif"></span>
        <span title="疑问" class="fw_face_span" imgurl="{faceBasePath}default/images/face/yiwen.gif"></span>
        <span title="偷笑" class="fw_face_span" imgurl="{faceBasePath}default/images/face/touxiao.gif"></span>
        <span title="吐" class="fw_face_span" imgurl="{faceBasePath}default/images/face/tu.gif"></span>
        <span title="调皮" class="fw_face_span" imgurl="{faceBasePath}default/images/face/tiaopi.gif"></span>
        <span title="挖鼻屎" class="fw_face_span" imgurl="{faceBasePath}default/images/face/koubi.gif"></span>
        <span title="无奈" class="fw_face_span" imgurl="{faceBasePath}default/images/face/piezui.gif"></span>
        <span title="快哭了" class="fw_face_span" imgurl="{faceBasePath}default/images/face/kuaikule.gif"></span>
        <span title="冷汗" class="fw_face_span" imgurl="{faceBasePath}default/images/face/lenghan.gif"></span>
        <span title="可爱" class="fw_face_span" imgurl="{faceBasePath}default/images/face/keai.gif"></span>
        <span title="糗大了" class="fw_face_span" imgurl="{faceBasePath}default/images/face/qiudale.gif"></span>
        <span title="嘘" class="fw_face_span" imgurl="{faceBasePath}default/images/face/xun.gif"></span>
        <span title="晕" class="fw_face_span" imgurl="{faceBasePath}default/images/face/yun.gif"></span>
        <span title="阴险" class="fw_face_span" imgurl="{faceBasePath}default/images/face/yinxian.gif"></span>
        <span title="委屈" class="fw_face_span" imgurl="{faceBasePath}default/images/face/weiqu.gif"></span>
        <span title="美味" class="fw_face_span" imgurl="{faceBasePath}default/images/face/jie.gif"></span>
        <span title="骷髅" class="fw_face_span" imgurl="{faceBasePath}default/images/face/kulou.gif"></span>
        <span title="猪头" class="fw_face_span" imgurl="{faceBasePath}default/images/face/zhutou.gif"></span>
        <span title="抱拳" class="fw_face_span" imgurl="{faceBasePath}default/images/face/baoquan.gif"></span>
        <span title="胜利" class="fw_face_span" imgurl="{faceBasePath}default/images/face/shengli.gif"></span>
        <span title="爱你" class="fw_face_span" imgurl="{faceBasePath}default/images/face/aini.gif"></span>
        <span title="顶你" class="fw_face_span" imgurl="{faceBasePath}default/images/face/qiang.gif"></span>
        <span title="弱" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ruo.gif"></span>
        <span title="不" class="fw_face_span" imgurl="{faceBasePath}default/images/face/no.gif"></span>
        <span title="勾引" class="fw_face_span" imgurl="{faceBasePath}default/images/face/gouying.gif"></span>
        <span title="握手" class="fw_face_span" imgurl="{faceBasePath}default/images/face/woshou.gif"></span>
        <span title="拳头" class="fw_face_span" imgurl="{faceBasePath}default/images/face/quantou.gif"></span>
        <span title="差劲" class="fw_face_span" imgurl="{faceBasePath}default/images/face/chajing.gif"></span>
        <span title="好的" class="fw_face_span" imgurl="{faceBasePath}default/images/face/ok.gif"></span>
        <span title="太阳" class="fw_face_span" imgurl="{faceBasePath}default/images/face/taiyang.gif"></span>
        <span title="月亮" class="fw_face_span" imgurl="{faceBasePath}default/images/face/yueliang.gif"></span>
    </div>
</div>